package com.github.biltudas1.dialsome;

import android.util.Log;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import java.util.Map;

public class MyFirebaseMessagingService extends FirebaseMessagingService {
    private static final String TAG = "DialSomeFCM";

    // Native method to notify the C++ Backend that a message arrived
    public native void onFCMMessageReceived(String type, String roomId, String email);
    private native void notifyNewToken(String token);

    /**
     * Called when a new token is generated.
     */
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        notifyNewToken(token);
        // In a real scenario, you'd send this to your /users/update-fcm endpoint
    }

    /**
     * Called when a message is received from the FastAPI backend.
     */
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        if (remoteMessage.getData().size() > 0) {
            Map<String, String> data = remoteMessage.getData();
            
            // Extract the fields from your new FastAPI payload
            String type = data.get("type");         // "incoming_call"
            String roomId = data.get("room_id");    // The UUIDv7/v4 generated by backend
            String callerEmail = data.get("caller_email");

            Log.d(TAG, "FCM Signal: " + type + " Room: " + roomId + " From: " + callerEmail);

            // Notify C++ layer
            onFCMMessageReceived(type, roomId, callerEmail);
        }
    }
}